apiVersion: batch/v1
kind: Job
metadata:
  name: guestbook-db-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"  
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Simulating migration..."
          sleep 20
          echo "Migration complete"
